mysociety/foi-for-councils

Procfile, Vagrantfile, script/provision-vagrant.sh
Makes starting all necessary processes easy and just one command.
Used `shoreman` instead of `foreman` because I couldn't figure out how
to add the binstub correctly in a way that both Rails and bundler are
happy with, and we don't use it in production so no real need to add a ruby
dependency here.
=> Add Procfile and shoreman

app/controllers/health/metrics_controller.rb, app/models/submission.rb, app/views/health/metrics/index.text.erb, config/routes.rb, spec/controllers/health/metrics_controller_spec.rb, spec/models/submission_spec.rb, spec/requests/health_spec.rb
Fixes #76 
Initial metrics endpoint. Covers the main Sidekiq stats, and a stat to check that we're getting reference numbers back from the Infreemation API.
=> [#76] Health endpoint

.travis.yml, app/controllers/foi/suggestions_controller.rb, app/models/curated_link.rb, app/services/foi_suggestion.rb, app/views/foi/suggestions/index.html.erb, spec/controllers/foi/suggestions_controller_spec.rb, spec/models/curated_link_spec.rb, spec/services/foi_suggestion_spec.rb
Part of #26 
Gives us word stemming and search ranking. Works by pulling out a list
of all keywords from the curated links. The keywords are matched with
the request to determine important words in the request. This word list
can then be used to generate a relevancy rank against the curated links
of which we need a greater than 0.75 match and we pick the top 3.
Tests need expanding. And need to run some performance analysis.
=> [#26] Implement Postgres search matching

Vagrantfile
When `.vagrant.yml` exists, but is empty, Vagrant fails to run:
$ vagrant reload
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.
Path: /Users/gareth/Code/foi-for-councils/Vagrantfile
Line number: 30
Message: TypeError: no implicit conversion of false into Hash
The problem is that when `.vagrant.yml` is empty, `YAML.load` returns
`false` rather than an empty `Hash`:
irb(main):033:0> YAML.load(File.read(settings_file_path))
This then gets supplied when we try to merge the `DEFAULTS` and the
`settings_file` hashes, causing the exception.
This commit ensures we always get a `Hash` assigned to `settings_file`
in the event that `.vagrant.yml` exists, but is empty.
=> Fix breakage when .vagrant.yml is empty

app/views/admin/curated_links/_preview.html.erb, app/views/admin/curated_links/edit.html.erb, app/views/admin/curated_links/new.html.erb
This extracts the "preview" component to its own partial. I think its
okay to have the layout duplication in the different views, as it feels
correct for the template to "own" its layout. The preview (like the
form) is a "component" that we're injecting in to that layout, so I
think it deserves its own template.
=> [#26] Extract duplication to partial

app/assets/javascripts/keyword-picker.js
This means, if you type a keyword in the box, but don’t press Enter, then the keyword will get saved before you click the form submit button.
Thanks to @crowbot for spotting this in #114!
=> Save current keyword when focus leaves Keywords input

app/controllers/admin/exports_controller.rb, app/controllers/concerns/findable_foi_request.rb, app/controllers/foi/suggestions_controller.rb, app/controllers/links_controller.rb, app/helpers/application_helper.rb, app/models/curated_link.rb, app/models/foi_request.rb, app/models/foi_suggestion.rb, app/models/submission.rb, app/services/generate_foi_suggestion.rb, app/views/admin/curated_links/index.html.erb, app/views/foi/suggestions/_suggestion.html.erb, config/initializers/application_controller_renderer.rb, config/routes.rb, db/migrate/20180605112908_create_foi_suggestions.rb, db/schema.rb, spec/controllers/admin/exports_controller_spec.rb, spec/controllers/foi/suggestions_controller_spec.rb, spec/controllers/links_controller_spec.rb, spec/factories/curated_links.rb, spec/factories/foi_requests.rb, spec/factories/foi_suggestions.rb, spec/factories/submissions.rb, spec/helpers/application_helper_spec.rb, spec/models/curated_link_spec.rb, spec/models/foi_request_spec.rb, spec/models/foi_suggestion_spec.rb, spec/models/submission_spec.rb, spec/services/generate_foi_suggestion_spec.rb, spec/support/context.rb
Closes #23 
Added:
- Suggestions displayed to users are now stored in the DB
- Recording when they are clicked or when the user goes on to continue their request
- Postgres query to collate statistics on suggestions
- Statistics CSV export for suggestion resources.
=> [#23] Store suggestions

.rubocop.yml, app/models/published_request.rb, db/migrate/20180605151909_create_published_requests.rb, db/migrate/20180605224444_add_cache_columns_to_published_requests.rb, db/migrate/20180606003046_add_reference_to_published_requests.rb, db/migrate/20180615085720_add_published_at_to_published_requests.rb, db/schema.rb, spec/factories/published_requests.rb, spec/models/published_request_spec.rb
Work on #25
* Adds a model (`PublishedRequest`) for caching disclosure log records from the API
* Service that handles importing the disclosure log from the API
* Doesn't incorporate in to `FoiSuggestion` – I'm not confident in getting that done quickly
To store data to later incorporate in to `FoiSuggestion`
* `PublishedRequest` is a duck type of `CuratedLink` for the purposes of `FoiSuggestion`
* This replaces #126 
* Decided to ditch checking if the `dateclosed` attribute has changed to detimine if the record needs updating and instead just update regardless
=> [#25] Add PublishedRequest model

app/controllers/admin/exports_controller.rb, app/models/curated_link.rb, app/models/published_request.rb, app/models/resource.rb, app/services/csv_exporter.rb, config/initializers/application_controller_renderer.rb, spec/controllers/admin/exports_controller_spec.rb, spec/factories/published_requests.rb, spec/factories/resources.rb, spec/models/curated_link_spec.rb, spec/models/published_request_spec.rb, spec/models/resource_spec.rb, spec/services/csv_exporter_spec.rb, spec/services/disclosure_log_spec.rb, spec/workers/import_disclosure_log_worker_spec.rb
Fixes #139
* Adds `PubishedRequest` analytics statistics to the suggestion export CSV
* Adds a `type` column to the CSV to distingish between `CuratedLink` and `PubishedRequest` records
To get statistics on how well past published requests are performing.
=> [#139] export PublishedRequest analytics

app/helpers/suggestions_helper.rb, app/views/foi/suggestions/_suggestion.html.erb, spec/helpers/suggestions_helper_spec.rb
We receive published requests in escaped and encoded JSON.
We need to clean this up before display, otherwise users see escaped
characters.
I've stripped all the HTML out so that it doesn't mess up our interface
– we just want the raw text.
Required for https://github.com/mysociety/foi-for-councils/issues/149.
**Before:**
**After:**
=> [#149] Format imported suggestion summaries

config/sidekiq.yml
Infreemation have requested that we import the disclosure log outside of
business hours.
We can't use `every` for this, as you can't specify the window, so I've
reverted to using `cron`-style scheduling.
I've tweaked the minute value so that we don't kick off multiple imports
at the same time. The imports that may return more results are kicked
off progressively later so that they have time to finish.
Fixes https://github.com/mysociety/foi-for-councils/issues/152
=> [#152] Import disclosure log between 00:00 and 06:00

app/helpers/suggestions_helper.rb, app/models/published_request.rb, app/models/summary.rb, spec/helpers/suggestions_helper_spec.rb, spec/models/published_request_spec.rb, spec/models/summary_spec.rb
We use the `summary` attribute when looking for suggestions to present
to the user, so cleaning it should help with search ranking.
Also means less processing at view render time, as now the helper is
just truncating, so a small performance boost too.
Fixes #157
=> [#157] Clean PublishedRequest#summary when caching

app/services/generate_foi_suggestion.rb, spec/services/generate_foi_suggestion_spec.rb
Fixes #200 
If keywords contain boolean operators characters then it could result in invalid tsquery. 
Given the keywords:
`a's & bs'`, `aye | hello`, `yes & ! no`, `foo&bar baz`, `two words`, `this & that thing`, `! nah1`, `!nah2`
These changes will turn the tsquery from:
`(a's & & & bs') | (aye & | & hello) |  (yes & & & ! & no) | (foo&bar & baz) | (two & words) | (this & & & that & thing) | (! & nah1) | (!nah2)`
which is invalid
To:
`('a''s'  &  'bs''') | ('aye'  |  'hello') | ('yes'  &  !  'no') | ('foo&bar baz') | ('two' & 'words') | ('this'  &  'that thing') | (!  'nah1') | ('!nah2')`
which is valid
=> [#200] tsquery boolean operators

script/provision-vagrant.sh
9a94734 introduced a Ruby version bump, but this version wasn't defined
in the version of ruby-build installed at the last provision.
This caused `vagrant provision` to fail as the expected ruby version
wasn't available.
This commit updates `rbenv` and `ruby-build` on `vagrant provision` so
that it always has up-to-date Ruby definitions.
=> Update rbenv and ruby-build on provision

.travis.yml
aba8b203bceecc4e5e411536e89b5411af6f410c updated bundler to fix a Travis
CI issue.
$ gem install bundler
$ gem update --system
Updating rubygems-update
Fetching: rubygems-update-3.1.1.gem (100%)
Successfully installed rubygems-update-3.1.1
Installing RubyGems 3.1.1
Successfully built RubyGem
Name: bundler
Version: 2.1.0
File: bundler-2.1.0.gem
bundler's executable "bundle" conflicts with /home/travis/.rvm/rubies/ruby-2.5.3/bin/bundle
Overwrite the executable? [yN]
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
=> Remove custom bundler versions

app/views/foi/requests/index.html.erb
The hackney.gov.uk URL no longer works. They link directly to the
Infreemation URL from their FOI info page [1] so we'll do the same here
for now.
Fixes https://github.com/mysociety/foi-for-councils/issues/287
[1] https://hackney.gov.uk/foi-request
=> Fix disclosure log URL

.github/workflows/ruby.yml
I can't see a reason why we wouldn't want to always use the latest for
simply installing Ruby.
Fixes CI failing due to deprecated commands [1].
[1] https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> Relax ruby/setup-ruby version specifier

app/controllers/foi/contacts_controller.rb, spec/controllers/foi/contacts_controller_spec.rb
Fixes #295 
When edit contact form route is loaded before any contact details have
been added an exception is raise:
```
An ActionView::Template::Error occurred in contacts#edit:
First argument in form cannot contain nil or be empty
app/views/foi/contacts/_form.html.erb:10
```
Added a before action callback to check and redirect to the new contact
form instead.
=> [#295] Fix exception on edit contact form

.rubocop.yml, app/services/queue_submission.rb, bin/spring
This means we can use do/end blocks with rescue.
See: https://bugs.ruby-lang.org/issues/12906
=> Update target Ruby version to 2.6

Gemfile, Gemfile.lock, app/models/contact.rb, app/models/curated_link.rb, app/models/foi_request.rb, app/models/foi_suggestion.rb, app/models/performance.rb, app/models/published_request.rb, app/models/resource.rb, app/models/submission.rb, app/models/summary.rb, app/models/user.rb, gemfiles/rails_main.gemfile.lock, lib/tasks/auto_annotate_models.rake
Annotate models with schema information
Installs and configures annotate to annotate models on `db:migrate` in
development mode only.
I never remember the schema, and while you can look in `db/schema.rb`
it's always easier to see just the specific table information alongside
the model that you're currently working on.
Mostly uses the defaults from `rails g:annotate:install`, but sets
`show_foreign_keys` and `show_indexes` to `false` since if you're
thinking about those you probably _do_ want to look in `db/schema.rb`.
Also excludes specs and factories as you don't tend to need a reminder
of the schema quite as frequently there.
Fixes https://github.com/mysociety/foi-for-councils/issues/387.
=> [#387] Annotate models with schema information

app/models/case_management/infreemation.rb, app/models/case_management/infreemation/published_request.rb, app/models/case_management/infreemation/submitted_request.rb, app/models/published_request.rb, app/services/deliver_submission.rb, app/services/disclosure_log.rb, spec/models/case_management/infreemation/published_request_spec.rb, spec/models/case_management/infreemation/submitted_request_spec.rb, spec/models/case_management/infreemation_spec.rb, spec/models/published_request_spec.rb, spec/services/deliver_submission_spec.rb, spec/services/disclosure_log_spec.rb
Extracts submissions of requests and importing the disclosure log as published requests to a Case Management backend in preparation for implementing a different Case Management Backend.
Currently retains `CaseManagement::Infreemation` as the default backend. Will need to implement a way of setting the current backend, but that can be done when we implement iCasework.
Fixes #383
=> [#383] Extract case management backend

app/models/case_management/infreemation/published_request.rb, spec/models/case_management/infreemation/published_request_spec.rb
The attribute in the payload is actually `subject`.
=> Fix mapping of Infreemation::PublishedRequest#title

app/models/case_management/icasework.rb, app/models/case_management/infreemation.rb, app/models/case_management/infreemation/published_request.rb, app/models/published_request.rb, app/services/disclosure_log.rb, db/migrate/20210316124123_add_case_management_to_published_requests.rb, db/schema.rb, spec/factories/published_requests.rb, spec/models/case_management/icasework_spec.rb, spec/models/case_management/infreemation/published_request_spec.rb, spec/models/case_management/infreemation_spec.rb, spec/models/published_request_spec.rb, spec/services/disclosure_log_spec.rb
Part of #385 
Fixes #405
Store the `CaseManagement` that was used to cache a `PublishedRequest` so that we can scope the `DisclosureLog` importer to only that `CaseManagement`.
Note that the Infreemation sandbox doesn't include a `url` attribute in the payload, but live does.
=> [#405] Add source to published requests

spec/services/disclosure_log_spec.rb
We didn't have a spec that tests that we cache newly available published
requests.
Used a reference of `FOI-999` to clearly distinguish it from the
single-number requests that we persist prior to the assertions.
=> Test that we persist new publish requests

app/models/case_management.rb, app/models/case_management/infreemation.rb, app/models/published_request.rb, spec/models/case_management/infreemation_spec.rb, spec/models/case_management_spec.rb, spec/models/published_request_spec.rb
If we don't have a URL stored, delegate to the `CaseManagement` to generate it.
NOOP for Infreemation since we always store a URL, but we'll need this for iCasework.
=> [#385] Delegate to CaseManagement for url generation

app/models/case_management/icasework/published_request.rb, spec/models/case_management/icasework/published_request_spec.rb
Try to pick the best date for `published_at`.
We _should_ have a `publish_in_the_disclosure_log_date` available, but
if not use `CaseStageStage1.DateCompleted`. Failing that, just use
`api_created_at`.
Fixes https://github.com/mysociety/foi-for-councils/issues/413.
=> [#413] Improve Icasework::PublishedRequest#publish_at

Gemfile, Gemfile.lock, app/models/case_management/icasework.rb, spec/models/case_management/icasework_spec.rb
Fixes https://github.com/mysociety/foi-for-councils/issues/423
We only even want to deal with documents which have been published on
the disclosure log.
The iCasework API describes this options as:
> Set "True" to return only documents that have been marked as public,
> or that have been published to the self service portal.
=> [#423] Retrieve documents flagged as self service

app/models/case_management/icasework/published_request.rb, spec/models/case_management/icasework/published_request_spec.rb
Extracts the PDF contents of documents to add to the summary text for
searchability.
Fixes https://github.com/mysociety/foi-for-councils/issues/386.
=> [#386] extract contents of documents for summary

.github/workflows/ci.yml
Uses Bundler 2.1 instead of 2.2 - so the prepackaged libv8 binary is used.
This reverts commit 9be97431cb61f4c3211b081d119328f84057e0cf.
=> Fix GitHub action libv8 install

app/controllers/admin/help_controller.rb, app/models/case_management/icasework.rb, app/models/case_management/infreemation.rb, app/views/admin/help/_breadcrumb.html.erb, app/views/admin/help/case_management/_icasework.html.erb, app/views/admin/help/index.html.erb, app/views/admin/show.html.erb, config/routes.rb, spec/controllers/admin/help_controller_spec.rb, spec/models/case_management/icasework_spec.rb, spec/models/case_management/infreemation_spec.rb, spec/views/admin/help/index.html.erb_spec.rb
Add basic admin help for iCasework
Reminders for how to use iCasework published requests as Suggestions.
I haven't implemented an Infreemation help page because it's not currently in use. This will obviously break if we do use Infreemation again, so we'll need to add `app/views/admin/help/case_management/_infreemation.html.erb` at that point.
=> Add iCasework admin help page

Gemfile.lock
For fixes to https://github.com/mysociety/icasework-ruby/issues/119
=> Bump icasework gem to v0.1.2
