mysociety/foi-for-councils

- .travis.yml
- config/database.yml-travis
Fixes #97 
Added Postgres and Redis services and updates bundler to fix travis-ci/travis-ci#9333
> Initial Travis configuration

- Gemfile
- Gemfile.lock
- app/models/submission.rb
- app/workers/deliver_submission_worker.rb
- spec/models/submission_spec.rb
- spec/support/sidekiq.rb
- spec/workers/deliver_submission_worker_spec.rb
Fixes #89 
Fixes #83 
Closes #98 
Work taken from PR #98 and comments in #89, merged the implementations and added specs.
One of the main specs from #98 wasn't doing [anything](https://github.com/mysociety/foi-for-councils/pull/98/files#r188967109) so this has been expanded and improved.
> [#89] Swtich to DB locking

- app/workers/clean_requests_worker.rb
- spec/workers/clean_requests_worker_spec.rb
Fixes #103
Check the requests are removed from the DB. This would of picked up a mistake in the method we were calling.
CI is going to fail due to #102 not being merged yet.
> [#103] Add spec clean request workers

- app/views/foi/contacts/_form.html.erb
- app/views/foi/requests/_form.html.erb
- app/views/foi/submissions/new.html.erb
This came across from the prototype and aren't used anymore.
> Remove JS session store classes

- app/controllers/admin/curated_links_controller.rb
- app/controllers/admin_controller.rb
- app/models/curated_link.rb
- app/views/admin/_breadcrumbs.html.erb
- app/views/admin/curated_links/_form.html.erb
- app/views/admin/curated_links/edit.html.erb
- app/views/admin/curated_links/index.html.erb
- app/views/admin/curated_links/new.html.erb
- app/views/application/_breadcrumbs.html.erb
- app/views/application/_flash.html.erb
- app/views/layouts/application.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20180524020418_create_curated_links.rb
- db/migrate/20180524031817_add_keywords_to_curated_links.rb
- db/schema.rb
- spec/controllers/admin/curated_links_controller_spec.rb
- spec/factories/curated_links.rb
- spec/models/curated_link_spec.rb
- spec/requests/admin_spec.rb
Admin sections extracted from #94.
Ready to merge; just making PR for visibility and CI after squashing.
> [#26] Curated links admin

- .gitmodules
- app/assets/javascripts/keyword-picker.js
- app/assets/stylesheets/keyword-picker.scss
- app/views/admin/curated_links/_form.html.erb
- app/views/admin/curated_links/index.html.erb
- app/views/layouts/application.html.erb
- bin/setup
- bin/update
- config/initializers/assets.rb
~~Sorry this looks like a huge PR – most of the added files are just the Taggle repo which I checked out into `/vendor`. My instinct was to add it as a git submodule instead, but that would probably introduce its a whole new tree of problems 😉~~
Anyway, here’s how it looks (with the normally-invisible input made semi-visible, so you can see what’s happening under the hood):
Part of #26.
> [#26] Keyword CSV input

- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/flashes.scss
- app/views/application/_flash.html.erb
> Styling for curated link flash messages

- config/logrotate-example
Fixes #124
Our internal automation will deploy a custom logrotate definition based on the presence of this file.
> Add a stub logroate-example file for deployments (fixes #124)

- app/services/queue_submission.rb
Fixes #89 
We are hitting an issue where the Sidekiq job runs too quickly and the
submission isn't retrievable as the DB write transaction hasn't
completed.
By moving the initial write outside the transaction we are ensuring it
completes before the next transaction is opened. This means the job will
always be able to find the queued submission and not exit early.
> [#89] Rework how we queue the deliver submission worker

- app/assets/javascripts/keyword-picker.js
> Insert Curated Link keyword input into correct tab order

- app/assets/javascripts/keyword-picker.js
- app/assets/stylesheets/forms.scss
- config/locales/en.yml
Give examples of `CuratedLink` data so that admins have a better sense
of what they need to input.
> Add example data to CuratedLink form

- app/assets/stylesheets/buttons.scss
- app/controllers/admin/curated_links_controller.rb
- app/models/curated_link.rb
- app/services/foi_suggestion.rb
- app/views/admin/curated_links/edit.html.erb
- app/views/admin/curated_links/index.html.erb
- db/migrate/20180606111720_add_destroyed_at_to_curated_links.rb
- db/schema.rb
- spec/controllers/admin/curated_links_controller_spec.rb
- spec/models/curated_link_spec.rb
- spec/rails_helper.rb
- spec/services/foi_suggestion_spec.rb
Fixes #27 
~~Needs some design on 7074425 and I'm not sure about how best to test 90f2f93.~~
> [#27] soft delete curated links

- app/services/foi_suggestion.rb
- spec/services/foi_suggestion_spec.rb
Fixes #132
Error was caused by curated links without keywords
> Prevent PG errors when generating suggestions

- app/assets/stylesheets/foi-preview.scss
- app/views/admin/_breadcrumbs.html.erb
- app/views/application/_breadcrumbs.html.erb
- app/views/foi/requests/_form.html.erb
- app/views/foi/requests/index.html.erb
- app/views/foi/submissions/new.html.erb
- app/views/foi/submissions/show.html.erb
- app/views/layouts/application.html.erb
Contains fixes for many issues described here https://github.com/mysociety/foi-for-councils/issues/22
> Accessibility fixes

- app/views/foi/submissions/show.html.erb
Update to latest stat.
Fixes https://github.com/mysociety/foi-for-councils/issues/154
> [#154] Update response stats

- app/models/published_request.rb
- app/services/disclosure_log.rb
- app/workers/import_disclosure_log_worker.rb
- db/migrate/20180723122932_add_api_created_at_to_published_requests.rb
- db/schema.rb
- spec/models/published_request_spec.rb
- spec/services/disclosure_log_spec.rb
- spec/workers/import_disclosure_log_worker_spec.rb
Fixes #141 
~~Need to address https://github.com/mysociety/foi-for-councils/issues/141#issuecomment-406662849~~
> [#141] Delete cached published requests when they become unpublished

- LICENSE.txt
Same as FixMyStreet and Alaveteli.
> Add GNU Affero GPL LICENSE

- app/views/foi/requests/index.html.erb
Help direct people there before they even start making a request.
Fixes https://github.com/mysociety/foi-for-councils/issues/230.
> Add link to disclosure log on the homepage

- .github/workflows/ci.yml
- .github/workflows/rubocop.yml
Split CI and Rubocop into two seporate actions and use reviewdog to run
Rubocop as we do on Alaveteli.
> Update GitHub actions

- app/assets/stylesheets/foi-suggestion.scss
> Correctly link to admin asset

- Gemfile
- Gemfile.lock
- app/models/case_management/icasework.rb
- app/models/case_management/icasework/submitted_request.rb
- config/initializers/icasework.rb
- gemfiles/rails_main.gemfile.lock
- spec/models/case_management/icasework/submitted_request_spec.rb
- spec/models/case_management/icasework_spec.rb
First part of https://github.com/mysociety/foi-for-councils/issues/385.
> [#385] iCasework: submit requests

- .github/workflows/ci.yml
- .gitignore
- app/models/case_management.rb
- app/models/case_management/icasework.rb
- app/models/case_management/infreemation.rb
- app/services/deliver_submission.rb
- bin/setup
- config/case_management.yml-example
- config/initializers/icasework.rb
- config/initializers/infreemation.rb
- spec/models/case_management/icasework_spec.rb
- spec/models/case_management/infreemation_spec.rb
- spec/models/case_management_spec.rb
- spec/services/deliver_submission_spec.rb
Fixes #396
~~Draft PR for visibility~~
> [#396] Configure which case management backend will be used

- app/models/case_management/icasework.rb
- spec/models/case_management/icasework_spec.rb
> Use new symbolised iCasework client params

- app/models/case_management/icasework.rb
- app/models/case_management/icasework/published_request.rb
- app/services/disclosure_log.rb
- config/initializers/case_management.rb
- spec/models/case_management/icasework/published_request_spec.rb
- spec/models/case_management/icasework_spec.rb
- spec/services/disclosure_log_spec.rb
Part of #385 
Fixes https://github.com/mysociety/foi-for-councils/issues/384
It work!
> [#385] iCasework: Import Published Requests

- app/views/foi/requests/index.html.erb
Update direct email address – Fixes #409.
Update disclosure log URL – Fixes #410.
> Go live details

- config/initializers/zeitwerk.rb
> Configure Zeitwerk autoloader for CSVExporter

- bin/setup
- bin/update
- docker-compose.yml
- docker/Dockerfile
- docker/bootstrap
- docker/createdb.sh
- docker/entrypoint.sh
- docker/reset
- docker/server
- docker/setup
Based on how we got Alaveteli docker setup
> Add docker compose development environment

- app/views/foi/requests/index.html.erb
Requested by Hackney, as link is broken and phone number is incorrect.
> Update intro text.

- .github/workflows/rubocop.yml
- Gemfile.lock
Bumping nio4r to compatible version too.
> Add bundler platforms for Apple systems
